// Mock profile data for development

import {
  MembershipStatus,
  FitnessStats,
  FitnessGoal,
  TrainingSession,
  ClassEnrollment,
  PaymentHistory,
  Achievement,
  ProfileMetrics,
} from "@/types/profile";

// export const mockUserProfile: UserProfile = {
//   id: "user_001",
//   firstName: "John",
//   lastName: "Anderson",
//   email: "john.anderson@email.com",
//   phone: "+1 (555) 123-4567",
//   avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
//   joinDate: "2023-06-15",
//   bio: "Fitness enthusiast | Marathon runner | Always pushing limits 💪",
//   address: {
//     street: "123 Fitness Street",
//     city: "San Francisco",
//     state: "CA",
//     zipCode: "94105",
//   },
// };

export const mockMembershipStatus: MembershipStatus = {
  id: "mem_001",
  planName: "Pro Annual",
  planType: "pro",
  status: "active",
  startDate: "2024-12-19",
  endDate: "2025-12-19",
  autoRenew: true,
  price: 599.99,
  billingCycle: "annual",
};

export const mockFitnessStats: FitnessStats = {
  id: "stats_001",
  userId: "user_001",
  weight: 78.5, // kg
  height: 180, // cm
  bmi: 24.2,
  bodyFat: 18.5, // percentage
  muscle: 42.3, // percentage
  workoutsThisWeek: 5,
  totalWorkouts: 127,
  lastMeasurement: "2025-12-17",
};

export const mockFitnessGoals: FitnessGoal[] = [
  {
    id: "goal_001",
    userId: "user_001",
    goal: "Reach 75kg weight",
    category: "weight",
    targetValue: 75,
    targetDate: "2025-03-31",
    progress: 65,
    status: "active",
    createdAt: "2024-12-01",
  },
  {
    id: "goal_002",
    userId: "user_001",
    goal: "Bench Press 150kg",
    category: "strength",
    targetValue: 150,
    targetDate: "2025-06-30",
    progress: 78,
    status: "active",
    createdAt: "2024-09-15",
  },
  {
    id: "goal_003",
    userId: "user_001",
    goal: "Complete 5K run under 22 minutes",
    category: "endurance",
    targetDate: "2025-05-31",
    progress: 42,
    status: "active",
    createdAt: "2024-11-01",
  },
  {
    id: "goal_004",
    userId: "user_001",
    goal: "Improve flexibility - Full split",
    category: "flexibility",
    targetDate: "2025-08-31",
    progress: 35,
    status: "active",
    createdAt: "2024-10-15",
  },
];

export const mockTrainingSessions: TrainingSession[] = [
  {
    id: "session_001",
    userId: "user_001",
    trainerName: "Sarah Mitchell",
    trainerId: "trainer_001",
    date: "2025-12-19",
    time: "10:00 AM",
    duration: 60,
    type: "Strength Training",
    notes: "Focus on upper body - shoulders & chest",
    status: "completed",
  },
  {
    id: "session_002",
    userId: "user_001",
    trainerName: "Marcus Johnson",
    trainerId: "trainer_002",
    date: "2025-12-21",
    time: "3:00 PM",
    duration: 45,
    type: "HIIT Cardio",
    notes: "Interval training for endurance",
    status: "upcoming",
  },
  {
    id: "session_003",
    userId: "user_001",
    trainerName: "Sarah Mitchell",
    trainerId: "trainer_001",
    date: "2025-12-24",
    time: "9:00 AM",
    duration: 60,
    type: "Full Body",
    notes: "Holiday week - maintain fitness",
    status: "upcoming",
  },
  {
    id: "session_004",
    userId: "user_001",
    trainerName: "Elena Rodriguez",
    trainerId: "trainer_003",
    date: "2025-12-17",
    time: "4:30 PM",
    duration: 50,
    type: "Core & Flexibility",
    notes: "Yoga fusion with core strength",
    status: "completed",
  },
  {
    id: "session_005",
    userId: "user_001",
    trainerName: "Marcus Johnson",
    trainerId: "trainer_002",
    date: "2025-12-14",
    time: "6:00 PM",
    duration: 60,
    type: "Boxing",
    notes: "Technique improvement session",
    status: "completed",
  },
];

export const mockClassEnrollments: ClassEnrollment[] = [
  {
    id: "enroll_001",
    classId: "class_001",
    className: "Morning Power Yoga",
    trainerName: "Elena Rodriguez",
    days: ["Monday", "Wednesday", "Friday"],
    time: "6:00 AM - 7:00 AM",
    capacity: 20,
    enrolled: 18,
    status: "active",
    joinedDate: "2024-09-10",
  },
  {
    id: "enroll_002",
    classId: "class_002",
    className: "HIIT Boot Camp",
    trainerName: "Marcus Johnson",
    days: ["Tuesday", "Thursday", "Saturday"],
    time: "5:30 PM - 6:30 PM",
    capacity: 25,
    enrolled: 22,
    status: "active",
    joinedDate: "2024-08-15",
  },
  {
    id: "enroll_003",
    classId: "class_003",
    className: "Strength & Conditioning",
    trainerName: "Sarah Mitchell",
    days: ["Monday", "Wednesday", "Friday"],
    time: "4:00 PM - 5:00 PM",
    capacity: 15,
    enrolled: 14,
    status: "active",
    joinedDate: "2024-07-20",
  },
  {
    id: "enroll_004",
    classId: "class_004",
    className: "Spin Cycle",
    trainerName: "David Park",
    days: ["Tuesday", "Thursday"],
    time: "6:00 PM - 7:00 PM",
    capacity: 30,
    enrolled: 28,
    status: "paused",
    joinedDate: "2024-10-05",
  },
];

export const mockPaymentHistory: PaymentHistory[] = [
  {
    id: "pay_001",
    userId: "user_001",
    amount: 49.99,
    date: "2025-12-19",
    description: "Monthly Membership - December",
    paymentMethod: "Visa ending in 1234",
    status: "completed",
    invoiceUrl: "/invoices/inv_001.pdf",
  },
  {
    id: "pay_002",
    userId: "user_001",
    amount: 599.99,
    date: "2025-12-01",
    description: "Annual Pro Membership Renewal",
    paymentMethod: "Visa ending in 1234",
    status: "completed",
    invoiceUrl: "/invoices/inv_002.pdf",
  },
  {
    id: "pay_003",
    userId: "user_001",
    amount: 100.0,
    date: "2025-11-15",
    description: "Personal Training Package (10 sessions)",
    paymentMethod: "Mastercard ending in 5678",
    status: "completed",
    invoiceUrl: "/invoices/inv_003.pdf",
  },
  {
    id: "pay_004",
    userId: "user_001",
    amount: 25.0,
    date: "2025-11-01",
    description: "Nutrition Consultation",
    paymentMethod: "Visa ending in 1234",
    status: "completed",
    invoiceUrl: "/invoices/inv_004.pdf",
  },
  {
    id: "pay_005",
    userId: "user_001",
    amount: 79.99,
    date: "2025-10-19",
    description: "Monthly Membership - October",
    paymentMethod: "Visa ending in 1234",
    status: "completed",
    invoiceUrl: "/invoices/inv_005.pdf",
  },
];

export const mockAchievements: Achievement[] = [
  {
    id: "ach_001",
    userId: "user_001",
    title: "Century Workout",
    description: "Completed 100 workouts",
    icon: "🏆",
    unlockedDate: "2025-11-30",
    type: "milestone",
  },
  {
    id: "ach_002",
    userId: "user_001",
    title: "Consistency King",
    description: "30-day workout streak",
    icon: "🔥",
    unlockedDate: "2025-12-15",
    type: "badge",
  },
  {
    id: "ach_003",
    userId: "user_001",
    title: "Calorie Crusher",
    description: "Burned 50,000 calories",
    icon: "⚡",
    unlockedDate: "2025-12-10",
    type: "milestone",
  },
  {
    id: "ach_004",
    userId: "user_001",
    title: "Early Bird",
    description: "50 early morning workouts",
    icon: "🌅",
    unlockedDate: "2025-12-01",
    type: "badge",
  },
  {
    id: "ach_005",
    userId: "user_001",
    title: "Personal Best",
    description: "Broke 5 personal records",
    icon: "💪",
    unlockedDate: "2025-11-20",
    type: "record",
  },
];

export const mockProfileMetrics: ProfileMetrics = {
  totalWorkouts: 127,
  totalHours: 98.5,
  streakDays: 42,
  caloriesBurned: 52340,
  personalRecords: 5,
};

// Export combined user data
export const mockUserData = {
  // profile: mockUserProfile,
  membership: mockMembershipStatus,
  stats: mockFitnessStats,
  goals: mockFitnessGoals,
  sessions: mockTrainingSessions,
  classes: mockClassEnrollments,
  payments: mockPaymentHistory,
  achievements: mockAchievements,
  metrics: mockProfileMetrics,
};
