import { User } from "./types";

export const MOCK_USERS: User[] = [
  {
    id: "user_001",
    name: "John Smith",
    email: "john.smith@example.com",
    password: null,
    emailVerified: new Date("2024-01-15"),
    image: null,
    role: "ADMIN",
    userStatus: "VERIFIED",
    stripeCustomerId: "cus_123456",
    subscriptionStatus: "ACTIVE",
    isBlocked: false,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-12-19"),
  },
  {
    id: "user_002",
    name: "Sarah Johnson",
    email: "sarah.johnson@example.com",
    password: null,
    emailVerified: new Date("2024-02-20"),
    image: null,
    role: "TRAINER",
    userStatus: "VERIFIED",
    stripeCustomerId: "cus_789012",
    subscriptionStatus: "ACTIVE",
    isBlocked: false,
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-12-19"),
  },
  {
    id: "user_003",
    name: "Michael Brown",
    email: "michael.brown@example.com",
    password: null,
    emailVerified: new Date("2024-03-10"),
    image: null,
    role: "CLIENT",
    userStatus: "VERIFIED",
    stripeCustomerId: "cus_345678",
    subscriptionStatus: "ACTIVE",
    isBlocked: false,
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-12-19"),
  },
  {
    id: "user_004",
    name: "Emma Davis",
    email: "emma.davis@example.com",
    password: null,
    emailVerified: null,
    image: null,
    role: "CLIENT",
    userStatus: "PENDING",
    stripeCustomerId: null,
    subscriptionStatus: "NONE",
    isBlocked: false,
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "user_005",
    name: "David Wilson",
    email: "david.wilson@example.com",
    password: null,
    emailVerified: new Date("2024-04-05"),
    image: null,
    role: "TRAINER",
    userStatus: "VERIFIED",
    stripeCustomerId: "cus_567890",
    subscriptionStatus: "ACTIVE",
    isBlocked: true,
    createdAt: new Date("2024-04-05"),
    updatedAt: new Date("2024-12-19"),
  },
  {
    id: "user_006",
    name: "Lisa Anderson",
    email: "lisa.anderson@example.com",
    password: null,
    emailVerified: new Date("2024-05-12"),
    image: null,
    role: "CLIENT",
    userStatus: "VERIFIED",
    stripeCustomerId: "cus_234567",
    subscriptionStatus: "ACTIVE",
    isBlocked: false,
    createdAt: new Date("2024-05-12"),
    updatedAt: new Date("2024-12-19"),
  },
  {
    id: "user_007",
    name: "James Martinez",
    email: "james.martinez@example.com",
    password: null,
    emailVerified: new Date("2024-06-18"),
    image: null,
    role: "CLIENT",
    userStatus: "VERIFIED",
    stripeCustomerId: "cus_901234",
    subscriptionStatus: "ACTIVE",
    isBlocked: false,
    createdAt: new Date("2024-06-18"),
    updatedAt: new Date("2024-12-19"),
  },
  {
    id: "user_008",
    name: "Patricia Garcia",
    email: "patricia.garcia@example.com",
    password: null,
    emailVerified: new Date("2024-07-22"),
    image: null,
    role: "ADMIN",
    userStatus: "VERIFIED",
    stripeCustomerId: "cus_678901",
    subscriptionStatus: "ACTIVE",
    isBlocked: false,
    createdAt: new Date("2024-07-22"),
    updatedAt: new Date("2024-12-19"),
  },
  {
    id: "user_009",
    name: "Robert Taylor",
    email: "robert.taylor@example.com",
    password: null,
    emailVerified: new Date("2024-08-30"),
    image: null,
    role: "CLIENT",
    userStatus: "REJECTED",
    stripeCustomerId: null,
    subscriptionStatus: "NONE",
    isBlocked: false,
    createdAt: new Date("2024-08-30"),
    updatedAt: new Date("2024-12-19"),
  },
  {
    id: "user_010",
    name: "Jennifer Lee",
    email: "jennifer.lee@example.com",
    password: null,
    emailVerified: new Date("2024-09-14"),
    image: null,
    role: "CLIENT",
    userStatus: "VERIFIED",
    stripeCustomerId: "cus_012345",
    subscriptionStatus: "ACTIVE",
    isBlocked: false,
    createdAt: new Date("2024-09-14"),
    updatedAt: new Date("2024-12-19"),
  },
  {
    id: "user_011",
    name: "Christopher White",
    email: "christopher.white@example.com",
    password: null,
    emailVerified: new Date("2024-10-08"),
    image: null,
    role: "TRAINER",
    userStatus: "VERIFIED",
    stripeCustomerId: "cus_123890",
    subscriptionStatus: "ACTIVE",
    isBlocked: false,
    createdAt: new Date("2024-10-08"),
    updatedAt: new Date("2024-12-19"),
  },
  {
    id: "user_012",
    name: "Angela Harris",
    email: "angela.harris@example.com",
    password: null,
    emailVerified: new Date("2024-11-03"),
    image: null,
    role: "CLIENT",
    userStatus: "PENDING",
    stripeCustomerId: null,
    subscriptionStatus: "NONE",
    isBlocked: false,
    createdAt: new Date("2024-11-03"),
    updatedAt: new Date("2024-12-19"),
  },
];

export const MOCK_SUBSCRIPTIONS = {
  user_001: {
    id: "sub_001",
    currentPeriodStart: new Date("2024-11-19"),
    currentPeriodEnd: new Date("2025-02-19"),
    status: "ACTIVE",
    planName: "Premium Annual",
  },
  user_002: {
    id: "sub_002",
    currentPeriodStart: new Date("2024-12-01"),
    currentPeriodEnd: new Date("2025-01-01"),
    status: "ACTIVE",
    planName: "Pro Monthly",
  },
  user_003: {
    id: "sub_003",
    currentPeriodStart: new Date("2024-12-10"),
    currentPeriodEnd: new Date("2025-01-10"),
    status: "ACTIVE",
    planName: "Standard Monthly",
  },
};
