import { Payment, PaymentStatus, PaymentMethod } from "./types/paymentTypes";

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: "PAY-001",
    userId: "USER-001",
    userName: "John Doe",
    userEmail: "john@example.com",
    amount: 99.99,
    currency: "USD",
    paymentMethod: "credit_card" as PaymentMethod,
    status: "pending" as PaymentStatus,
    proofUrl: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=500",
    proofType: "screenshot",
    claimDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    description: "3-Month Premium Membership",
    transactionRef: "TXN-2025-001",
    notes: "Payment made via Stripe",
    confirmedDate: null,
    deniedDate: null,
    rejectedDate: null,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "PAY-002",
    userId: "USER-002",
    userName: "Sarah Smith",
    userEmail: "sarah@example.com",
    amount: 49.99,
    currency: "USD",
    paymentMethod: "bank_transfer" as PaymentMethod,
    status: "confirmed" as PaymentStatus,
    proofUrl: "https://images.unsplash.com/photo-1611987841239-56fb0dbb8b59?w=500",
    proofType: "bank_statement",
    claimDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    description: "1-Month Standard Membership",
    transactionRef: "TXN-2025-002",
    notes: "Bank transfer confirmed",
    confirmedDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    deniedDate: null,
    rejectedDate: null,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "PAY-003",
    userId: "USER-003",
    userName: "Mike Johnson",
    userEmail: "mike@example.com",
    amount: 149.99,
    currency: "USD",
    paymentMethod: "digital_wallet" as PaymentMethod,
    status: "pending" as PaymentStatus,
    proofUrl: "https://images.unsplash.com/photo-1563013264-8a94f4b06899?w=500",
    proofType: "receipt",
    claimDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    description: "6-Month Elite Membership",
    transactionRef: "TXN-2025-003",
    notes: "PayPal transaction",
    confirmedDate: null,
    deniedDate: null,
    rejectedDate: null,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "PAY-004",
    userId: "USER-004",
    userName: "Emma Wilson",
    userEmail: "emma@example.com",
    amount: 79.99,
    currency: "USD",
    paymentMethod: "credit_card" as PaymentMethod,
    status: "rejected" as PaymentStatus,
    proofUrl: "https://images.unsplash.com/photo-1526307260143-a3cdc3cf0cb0?w=500",
    proofType: "screenshot",
    claimDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    description: "3-Month Premium Membership",
    transactionRef: "TXN-2025-004",
    notes: "Proof invalid - card number partially visible",
    confirmedDate: null,
    deniedDate: null,
    rejectedDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "PAY-005",
    userId: "USER-005",
    userName: "Alex Brown",
    userEmail: "alex@example.com",
    amount: 199.99,
    currency: "USD",
    paymentMethod: "cryptocurrency" as PaymentMethod,
    status: "pending" as PaymentStatus,
    proofUrl: "https://images.unsplash.com/photo-1642104704074-dbe8ddb8e6e7?w=500",
    proofType: "transaction_hash",
    claimDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    description: "12-Month Ultimate Package",
    transactionRef: "TXN-2025-005",
    notes: "Bitcoin transaction pending verification",
    confirmedDate: null,
    deniedDate: null,
    rejectedDate: null,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "PAY-006",
    userId: "USER-006",
    userName: "Lisa Anderson",
    userEmail: "lisa@example.com",
    amount: 59.99,
    currency: "USD",
    paymentMethod: "bank_transfer" as PaymentMethod,
    status: "denied" as PaymentStatus,
    proofUrl: "https://images.unsplash.com/photo-1604987556165-8184c3d925b4?w=500",
    proofType: "bank_statement",
    claimDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    description: "1-Month Basic Membership",
    transactionRef: "TXN-2025-006",
    notes: "Amount mismatch - claimed $59.99 but proof shows $49.99",
    confirmedDate: null,
    deniedDate: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    rejectedDate: null,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "PAY-007",
    userId: "USER-007",
    userName: "David Martinez",
    userEmail: "david@example.com",
    amount: 89.99,
    currency: "USD",
    paymentMethod: "credit_card" as PaymentMethod,
    status: "confirmed" as PaymentStatus,
    proofUrl: "https://images.unsplash.com/photo-1621905167918-48416bd8575a?w=500",
    proofType: "screenshot",
    claimDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    description: "3-Month Premium Membership",
    transactionRef: "TXN-2025-007",
    notes: "Visa card payment confirmed",
    confirmedDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    deniedDate: null,
    rejectedDate: null,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "PAY-008",
    userId: "USER-008",
    userName: "Jennifer Lee",
    userEmail: "jennifer@example.com",
    amount: 129.99,
    currency: "USD",
    paymentMethod: "digital_wallet" as PaymentMethod,
    status: "pending" as PaymentStatus,
    proofUrl: "https://images.unsplash.com/photo-1550565231-eb88a09db773?w=500",
    proofType: "receipt",
    claimDate: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    description: "6-Month Elite Package",
    transactionRef: "TXN-2025-008",
    notes: "Google Pay transaction",
    confirmedDate: null,
    deniedDate: null,
    rejectedDate: null,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "PAY-009",
    userId: "USER-009",
    userName: "Robert Taylor",
    userEmail: "robert@example.com",
    amount: 169.99,
    currency: "USD",
    paymentMethod: "credit_card" as PaymentMethod,
    status: "confirmed" as PaymentStatus,
    proofUrl: "https://images.unsplash.com/photo-1575444758702-4a6b7f7fc032?w=500",
    proofType: "screenshot",
    claimDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    description: "6-Month Premium + Personal Training",
    transactionRef: "TXN-2025-009",
    notes: "Mastercard payment verified",
    confirmedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    deniedDate: null,
    rejectedDate: null,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "PAY-010",
    userId: "USER-010",
    userName: "Michelle Garcia",
    userEmail: "michelle@example.com",
    amount: 39.99,
    currency: "USD",
    paymentMethod: "bank_transfer" as PaymentMethod,
    status: "pending" as PaymentStatus,
    proofUrl: "https://images.unsplash.com/photo-1578892676951-f3db0592a2a0?w=500",
    proofType: "bank_statement",
    claimDate: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    description: "1-Month Basic",
    transactionRef: "TXN-2025-010",
    notes: "Bank transfer initiated",
    confirmedDate: null,
    deniedDate: null,
    rejectedDate: null,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "PAY-011",
    userId: "USER-011",
    userName: "Christopher White",
    userEmail: "christopher@example.com",
    amount: 109.99,
    currency: "USD",
    paymentMethod: "digital_wallet" as PaymentMethod,
    status: "rejected" as PaymentStatus,
    proofUrl: "https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=500",
    proofType: "receipt",
    claimDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    description: "3-Month Elite",
    transactionRef: "TXN-2025-011",
    notes: "Receipt does not match transaction amount",
    confirmedDate: null,
    deniedDate: null,
    rejectedDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "PAY-012",
    userId: "USER-012",
    userName: "Amanda Harris",
    userEmail: "amanda@example.com",
    amount: 249.99,
    currency: "USD",
    paymentMethod: "credit_card" as PaymentMethod,
    status: "pending" as PaymentStatus,
    proofUrl: "https://images.unsplash.com/photo-1614027164847-1b28cfe1df60?w=500",
    proofType: "screenshot",
    claimDate: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    description: "12-Month Ultimate + All Perks",
    transactionRef: "TXN-2025-012",
    notes: "Premium card transaction",
    confirmedDate: null,
    deniedDate: null,
    rejectedDate: null,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "PAY-013",
    userId: "USER-001",
    userName: "John Doe",
    userEmail: "john@example.com",
    amount: 69.99,
    currency: "USD",
    paymentMethod: "digital_wallet" as PaymentMethod,
    status: "confirmed" as PaymentStatus,
    proofUrl: "https://images.unsplash.com/photo-1616763355603-9755a6ceb0f6?w=500",
    proofType: "receipt",
    claimDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Personal Training Session",
    transactionRef: "TXN-2025-013",
    notes: "Apple Pay confirmed",
    confirmedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    deniedDate: null,
    rejectedDate: null,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "PAY-014",
    userId: "USER-014",
    userName: "Thomas Robinson",
    userEmail: "thomas@example.com",
    amount: 89.99,
    currency: "USD",
    paymentMethod: "credit_card" as PaymentMethod,
    status: "denied" as PaymentStatus,
    proofUrl: "https://images.unsplash.com/photo-1632766486701-71a66c358dce?w=500",
    proofType: "screenshot",
    claimDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    description: "3-Month Premium",
    transactionRef: "TXN-2025-014",
    notes: "Proof appears to be duplicate - already processed payment",
    confirmedDate: null,
    deniedDate: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    rejectedDate: null,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "PAY-015",
    userId: "USER-015",
    userName: "Victoria Clark",
    userEmail: "victoria@example.com",
    amount: 119.99,
    currency: "USD",
    paymentMethod: "bank_transfer" as PaymentMethod,
    status: "pending" as PaymentStatus,
    proofUrl: "https://images.unsplash.com/photo-1633356715686-0c68b6d99ff0?w=500",
    proofType: "bank_statement",
    claimDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    description: "3-Month Elite Membership",
    transactionRef: "TXN-2025-015",
    notes: "International transfer",
    confirmedDate: null,
    deniedDate: null,
    rejectedDate: null,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
];
